# Generated by Django 5.1.7 on 2025-11-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consumer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="consumer_uuid",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="resource_provider_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.resourceprovideraccount",
            ),
        ),
    ]
