# Generated by Django 5.0.8 on 2024-11-22 16:00

from django.db import migrations, models


def copy_resource_hours(apps, schema_editor):
    CreditAllocationResource = apps.get_model(
        "coral_credits", "CreditAllocationResource"
    )
    for resource in CreditAllocationResource.objects.all():
        resource.original_resource_hours = resource.resource_hours
        resource.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditallocationresource",
            name="original_resource_hours",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
