# Generated by Django 5.0.1 on 2024-02-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_creditallocationresource_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumer",
            old_name="consume_ref",
            new_name="consumer_ref",
        ),
        migrations.AlterUniqueTogether(
            name="consumer",
            unique_together={("consumer_ref", "resource_provider")},
        ),
        migrations.AlterField(
            model_name="creditallocationresource",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="api.creditallocation",
            ),
        ),
        migrations.AlterField(
            model_name="creditallocationresource",
            name="resource_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.resourceclass",
            ),
        ),
        migrations.AlterField(
            model_name="resourceconsumptionrecord",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="api.consumer",
            ),
        ),
        migrations.AlterField(
            model_name="resourceconsumptionrecord",
            name="resource_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.resourceclass",
            ),
        ),
    ]
