# Generated by Django 5.1.7 on 2025-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_consumer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditallocationresource",
            name="allocated_resource_hours",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
