# Generated by Django 5.1.7 on 2025-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_creditallocationresource_allocated_resource_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditallocationresource",
            name="allocated_resource_hours",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="creditallocationresource",
            name="resource_hours",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="resourceconsumptionrecord",
            name="resource_hours",
            field=models.IntegerField(),
        ),
    ]
