# Generated by Django 5.0.6 on 2024-07-04 16:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_resourceprovideraccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="consumer_uuid",
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consumer",
            name="user_ref",
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
    ]
