# Generated by Django 5.0.6 on 2024-07-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_consumer_consumer_uuid_consumer_user_ref"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consumer",
            unique_together={("consumer_uuid", "resource_provider_account")},
        ),
    ]
