{
 "title": "Coral Credits Operator Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ProjectID",
    "label": "Project ID",
    "query": {
     "query": "label_values(coral_credits_allocation_hours_per_project,project_id)"
    }
   },
   {
    "name": "ResourceClass",
    "label": "Resource Class",
    "query": {
     "query": "label_values(coral_credits_allocation_hours_per_project,resource_class)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Allocation Hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total $ResourceClass Allocation Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "ResourceClass",
   "targets": [
    {
     "expr": "sum by(resource_class) (coral_credits_allocation_hours_per_project{resource_class=\"$ResourceClass\"})",
     "legendFormat": "Total Allocated"
    },
    {
     "expr": "sum by(resource_class) (coral_credits_allocation_hours_reserved_per_project{resource_class=~\"$ResourceClass\"})",
     "legendFormat": "Already Reserved"
    }
   ]
  },
  {
   "title": "Total Allocation Hours Per Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Total $ResourceClass Allocation Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "ResourceClass",
   "targets": [
    {
     "expr": "coral_credits_allocation_hours_per_project{project_id=~\"$ProjectID\", resource_class=~\"$ResourceClass\"}",
     "legendFormat": "Total {{project_id}}"
    }
   ]
  },
  { "title": "Free Allocation Hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Free $ResourceClass Allocation Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "repeat": "ResourceClass",
   "targets": [
    {
     "expr": "coral_credits_allocation_hours_free_per_project{project_id=~\"$ProjectID\", resource_class=~\"$ResourceClass\"}",
     "legendFormat": "{{project_id}}"
    }
   ]
  },
  { "title": "Reserved Allocation Hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Reserved $ResourceClass Allocation Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "repeat": "ResourceClass",
   "targets": [
    {
     "expr": "coral_credits_allocation_hours_reserved_per_project{project_id=~\"$ProjectID\", resource_class=~\"$ResourceClass\"}",
     "legendFormat": "{{project_id}}"
    }
   ]
  }
 ]
}